// <auto-generated />
using System;
using EuniceMed.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuniceMed.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EuniceMed.Api.Models.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte>("Strength")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Collection_Slug");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "care",
                            SortOrder = 1,
                            Strength = (byte)1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "protect",
                            SortOrder = 2,
                            Strength = (byte)2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "advance",
                            SortOrder = 3,
                            Strength = (byte)3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EuniceMed.Api.Models.Entities.CollectionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionTr");

                    b.ToTable("CollectionTranslations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21111111-0000-0000-0000-000000000001"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Description = "Everyday light relief for comfort through ordinary days.",
                            Locale = "en",
                            Name = "Care"
                        },
                        new
                        {
                            Id = new Guid("21111111-0000-0000-0000-000000000002"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000001"),
                            Description = "日常輕度緩解，為平常的每一天提供舒適支撐。",
                            Locale = "zh-TW",
                            Name = "日常照護"
                        },
                        new
                        {
                            Id = new Guid("21111111-0000-0000-0000-000000000003"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Description = "Strong support for high-load activity and demanding movement.",
                            Locale = "en",
                            Name = "Protect"
                        },
                        new
                        {
                            Id = new Guid("21111111-0000-0000-0000-000000000004"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000002"),
                            Description = "高強度活動的強力支撐，因應大負荷的動作需求。",
                            Locale = "zh-TW",
                            Name = "強力防護"
                        },
                        new
                        {
                            Id = new Guid("21111111-0000-0000-0000-000000000005"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Description = "Rehabilitation-oriented, targeted protection for recovery.",
                            Locale = "en",
                            Name = "Advance"
                        },
                        new
                        {
                            Id = new Guid("21111111-0000-0000-0000-000000000006"),
                            CollectionId = new Guid("11111111-0000-0000-0000-000000000003"),
                            Description = "復健導向的針對性保護，協助恢復過程。",
                            Locale = "zh-TW",
                            Name = "進階復健"
                        });
                });

            modelBuilder.Entity("EuniceMed.Api.Models.Entities.CollectionTranslation", b =>
                {
                    b.HasOne("EuniceMed.Api.Models.Entities.Collection", "Collection")
                        .WithMany("Translations")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("EuniceMed.Api.Models.Entities.Collection", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
